version: '3.5'
services:
  db:
    build: postgresql
    image: postgresql:1.0.0
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    networks:
      - clevertec_ntwrk
  pgadmin:
    build: pgadmin
    image: pgadmin:1.0.0
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      - clevertec_ntwrk
  news:
    build: clevertec_final
    image: clevertec_final-1.0.0
    ports:
      - "80:8080"
    depends_on:
      - redis
      - pgadmin
    restart: always
    networks:
      - clevertec_ntwrk
  user-service:
    build: user_service
    image: user_service:1.0.0
    restart: always
    networks:
      - clevertec_ntwrk
  config-service:
    build: config-service
    image: config-service:1.0.0
    restart: always
    networks:
      - clevertec_ntwrk
  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - clevertec_ntwrk
networks:
  clevertec_ntwrk:
    name: clevertec_ntwrk