server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Grishagrishaa/config-repository.git
          username: Grishagrishaa
          password: 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
          default-label: "master"
